version: '3.1'

services:

  next:
    build: 
      dockerfile: ./next/Dockerfile
    env_file: ./next/.env
    ports:
     - 3000:3000
    volumes:
      - ./next/pages:/app/pages
      - ./next/public:/app/public
      - ./next/styles:/app/styles

  strapi:
    build: 
      dockerfile: ./strapi/Dockerfile
    ports:
     - 1337:1337