version: '3.1'

services:

  next:
    build: 
      dockerfile: ./next/Dockerfile.production
    env_file: ./next/.env
    ports:
     - 8080:3000

  strapi:
    build: 
      dockerfile: ./strapi/Dockerfile
    ports:
     - 1337:1337